# Generated by Django 3.1.2 on 2020-10-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('days', models.IntegerField()),
                ('stops', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('ship_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('release', models.DateField()),
                ('deadline', models.DateField()),
                ('team', models.IntegerField()),
                ('economy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luxury_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('excursion_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('departure', models.DateTimeField(auto_now_add=True)),
                ('economy_pass', models.IntegerField()),
                ('business_pass', models.IntegerField()),
                ('luxurious_pass', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProjec.route')),
                ('ship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProjec.ship')),
            ],
        ),
    ]
