# Generated by Django 3.1.2 on 2020-10-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
