# Generated by Django 3.1.2 on 2020-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjec', '0003_auto_20201005_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.IntegerField(null=True),
        ),
    ]
