# Generated by Django 3.1.2 on 2020-10-05 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjec', '0004_auto_20201005_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='route',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.IntegerField(),
        ),
    ]
