# Generated by Django 3.1.2 on 2020-10-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjec', '0005_auto_20201005_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='route_id',
            new_name='e_route_id',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='ship_id',
            new_name='e_ship_id',
        ),
    ]
